# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cristian Piqué
tagline:          'Cristian Piqué'
description:      'My personal blog of tech and life.'
url:              https://cpique.github.io/

author:
  name:           'Cristian Piqué'
  url:            https://cpique.github.io/

paginate:         2
google_analytics: 'UA-110928553-1'
emailme:          mailto:cristian.andres.pique@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/cpique/cpique.github.io/

tags:

github_username:  cpique
facebook_username: cristian.pique.1
linkedin_username: cristian-piqué


