# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cristian Piqué
tagline:          'Cristian Piqué'
description:      'My personal blog of tech and life.'
url:              http://longqian.me/

author:
  name:           'Long Qian'
  url:            http://longqian.me/

paginate:         2
google_analytics: 'UA-91425204-3'
bing_seo:		  'ECA8D4503D79297E7BB223666F18CAF8'
emailme:          mailto:cristian.andres.pique@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/cpique/cpique.github.io/

tags:

github_username:  cpique
facebook_username: cristian.pique.1
linkedin_username: cristian-piqué


